export const GOVERNORATES: { code: string; fr: string; ar: string }[] = [
  { code: "tunis", fr: "Tunis", ar: "تونس" },
  { code: "ariana", fr: "Ariana", ar: "أريانة" },
  { code: "ben-arous", fr: "Ben Arous", ar: "بن عروس" },
  { code: "manouba", fr: "La Manouba", ar: "منوبة" },
  { code: "nabeul", fr: "Nabeul", ar: "نابل" },
  { code: "zaghouan", fr: "Zaghouan", ar: "زغوان" },
  { code: "bizerte", fr: "Bizerte", ar: "بنزرت" },
  { code: "beja", fr: "Béja", ar: "باجة" },
  { code: "jendouba", fr: "Jendouba", ar: "جندوبة" },
  { code: "kef", fr: "Le Kef", ar: "الكاف" },
  { code: "siliana", fr: "Siliana", ar: "سليانة" },
  { code: "sousse", fr: "Sousse", ar: "سوسة" },
  { code: "monastir", fr: "Monastir", ar: "المنستير" },
  { code: "mahdia", fr: "Mahdia", ar: "المهدية" },
  { code: "sfax", fr: "Sfax", ar: "صفاقس" },
  { code: "kairouan", fr: "Kairouan", ar: "القيروان" },
  { code: "kasserine", fr: "Kasserine", ar: "القصرين" },
  { code: "sidi-bouzid", fr: "Sidi Bouzid", ar: "سيدي بوزيد" },
  { code: "gabes", fr: "Gabès", ar: "قابس" },
  { code: "medenine", fr: "Médenine", ar: "مدنين" },
  { code: "tataouine", fr: "Tataouine", ar: "تطاوين" },
  { code: "gafsa", fr: "Gafsa", ar: "قفصة" },
  { code: "tozeur", fr: "Tozeur", ar: "توزر" },
  { code: "kebili", fr: "Kébili", ar: "قبلي" },
];
